# Generated by Django 4.2.21 on 2025-05-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seller_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ продавца'),
        ),
    ]
